deployment of SDK docs
RasaHQ/rasa-sdk pull request #264
Opened 2020-09-03 13:07 UTC by erohmensing

**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/master/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

2020-09-04 09:49 UTC, m-vdb commented
@erohmensing you need a file named `docs/static/_redirects`, like we do here: https://github.com/RasaHQ/rasa/blob/master/docs/static/_redirects

2020-09-04 09:50 UTC, m-vdb commented on docs/docusaurus.config.js
> +  baseUrl: '/docs/rasa-sdk/next/',
you can remove the next right away, since this URL doesn't exist at all today

2020-09-04 15:27 UTC, erohmensing commented on docs/package.json
>    },
I see what you mean now about the dependencies! I shouldnt have added them before, it just makes it more work to try to get the deployment working. We will almost certainly use them, which is why i've left the comments in the docusaurus config to remind me where to put them back in, but i'll update those on the content branch: https://github.com/RasaHQ/rasa-sdk/pull/254/files

Sorry for the confusion on the last one 😄

2020-09-07 07:49 UTC, m-vdb requested changes
Nice work @erohmensing ! a couple of comments to address before it's mergeable :)

2020-09-09 15:27 UTC, erohmensing commented
erp, forgot to re-request a review!

2020-09-09 15:56 UTC, m-vdb approved these changes
🥇

2020-09-10 13:04 UTC, merged