Merge 2.x docs versions
RasaHQ/rasa-sdk pull request #626
Opened 2021-12-07 17:22 UTC by m-vdb

**Proposed changes**:
- ...

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

2021-12-08 13:43 UTC, m-vdb commented on .github/workflows/continous-integration.yml
> -name: Continous Integration
This workflow was renamed on `main` (there was a typo in the name) but the `documentation` branch wasn't cleaned up.

2021-12-09 18:17 UTC, melindaloubser1 requested changes
Thanks for the links, made that way  more review-able!
Just one thing: This file https://github.com/RasaHQ/rasa-sdk/pull/626/files#diff-62c30ba09428f9c2115eab0aac2ad7ea250d1a22efdf60ec6471ff9b469ea10e
Should have a note that the `--log-file` argument was only introduced in 2.3.0.

Other than that all good!

2021-12-10 07:57 UTC, m-vdb commented
fixed with 28f741a

2021-12-10 09:53 UTC, melindaloubser1 approved these changes
🚀

2021-12-10 12:34 UTC, merged