[ATO-711] Port handle deflated webhook request to 3.2.x
RasaHQ/rasa-sdk pull request #929
Opened 2023-02-01 15:35 UTC by radovanZRasa

**Proposed changes**:
Add capability to handle deflated body of a HTTP request.

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation in the [rasaHQ/rasa](https://github.com/rasaHQ/rasa)
- [ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa-sdk/tree/main/changelog) for instructions)
- [ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa-sdk#code-style) for instructions)

2023-02-01 15:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/rasa-sdk?pullRequest=929) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/rasa-sdk?pullRequest=929) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/rasa-sdk?pullRequest=929) it.</sub>

2023-02-02 14:16 UTC, m-vdb reviewed
I'll let Tom or Anca review the actual code ;)

2023-02-02 14:16 UTC, m-vdb commented on .github/workflows/continuous-integration.yml
> -
can you remove [these 2 make targets](https://github.com/RasaHQ/rasa-sdk/blob/main/Makefile#L58-L67) too? I think they're unused now

2023-02-06 10:22 UTC, m-vdb requested changes

2023-02-06 10:22 UTC, m-vdb commented on rasa_sdk/endpoint.py
>      async def webhook(request: Request) -> HTTPResponse:
[the test is missing](https://github.com/RasaHQ/rasa-sdk/pull/925/files#diff-adf6af4744d4ee23f8b03b6fddcd7ca0ae330cd2ba8e3dc39c834ee76dbe47de)

2023-02-06 13:29 UTC, m-vdb approved these changes

2023-02-06 17:54 UTC, tmbo approved these changes
lgtm

2023-02-07 12:48 UTC, merged